let ON_CONNECT = 'connect';
let ON_DISCONNECT = 'disconnect';
let IS_USER_ONLINE = 'is_user_online';
let INDIVIDUAL_CHAT_MESSAGE = 'individual_chat_message';
let GROUP_CHAT_MESSAGE = 'group_chat_message';
let RECEIVE_MESSAGE = 'receive_message';
let MESSAGE_FROM_SERVER = 'message_from_server';
let STATUS_CODE_MESSAGE_NOT_SENT = 1001;
let STATUS_CODE_MESSAGE_SENT = 2002;
let STATUS_CODE_MESSAGE_DELIVERED = 3003;
let STATUS_CODE_MESSAGE_READ = 4004;


module.exports ={
    ON_CONNECT: ON_CONNECT,
    ON_DISCONNECT: ON_DISCONNECT,
    IS_USER_ONLINE: IS_USER_ONLINE,
    INDIVIDUAL_CHAT_MESSAGE: INDIVIDUAL_CHAT_MESSAGE,
    GROUP_CHAT_MESSAGE: GROUP_CHAT_MESSAGE,
    RECEIVE_MESSAGE: RECEIVE_MESSAGE,
    MESSAGE_FROM_SERVER: MESSAGE_FROM_SERVER,
    STATUS_CODE_MESSAGE_NOT_SENT: STATUS_CODE_MESSAGE_NOT_SENT,
    STATUS_CODE_MESSAGE_SENT: STATUS_CODE_MESSAGE_SENT,
    STATUS_CODE_MESSAGE_DELIVERED: STATUS_CODE_MESSAGE_DELIVERED,
    STATUS_CODE_MESSAGE_READ: STATUS_CODE_MESSAGE_READ
}